gutter = Team.create(name: "Gutter", email: "Dogshow_Drop_Out@hotmail.com", password: "pw")
spare = Team.create(name: "Spare", email: "TheRocketeer@yahoo.com", password: "pw")
Tournament.create(name: "Lodi Lanes", location: "Lodi, California", date: "12/22/2020", team_id: gutter.id)
Tournament.create(name: "AMF Boulevard Lanes", location: "Petaluma, California", date: "11/24/2020", team_id: gutter.id)
Tournament.create(name: "Lanesplitter", location: "Oakland, California", date: "11/15/2020", team_id: spare.id)